In [3]:
import numpy as np
import csv
import math

# 数据加载

In [4]:
data=[]
with open('data.csv','r') as f:
    reader = csv.reader(f)
    for row in reader:
        if row[0]!="x1":
            data.append(row)
data = np.array(data,dtype='float')

y  = np.arange(30)
for i in y:
    y[i] = i/10
data

array([[-5.01, -8.12, -3.68],
       [-5.43, -3.48, -3.54],
       [ 1.08, -5.52,  1.66],
       [ 0.86, -3.78, -4.11],
       [-2.67,  0.63,  7.39],
       [ 4.94,  3.29,  2.08],
       [-2.51,  2.09, -2.59],
       [-2.25, -2.13, -6.94],
       [ 5.56,  2.86, -2.26],
       [ 1.03, -3.33,  4.33],
       [-0.91, -0.18, -0.05],
       [ 1.3 , -2.06, -3.53],
       [-7.75, -4.54, -0.95],
       [-5.47,  0.5 ,  3.92],
       [ 6.14,  5.72, -4.85],
       [ 3.6 ,  1.26,  4.36],
       [ 5.37, -4.63, -3.65],
       [ 7.18,  1.46, -6.66],
       [-7.39,  1.17,  6.3 ],
       [-7.5 , -6.32, -0.31],
       [ 5.35,  2.26,  8.13],
       [ 5.12,  3.22, -2.66],
       [-1.34, -5.31, -9.87],
       [ 4.48,  3.42,  5.19],
       [ 7.11,  2.39,  9.21],
       [ 7.17,  4.33, -0.98],
       [ 5.75,  3.97,  6.65],
       [ 0.77,  0.27,  2.41],
       [ 0.9 , -0.43, -8.71],
       [ 3.52, -0.36,  6.43]])

In [5]:
import matplotlib.pyplot as plt
from mpl_toolkits import mplot3d
fig = plt.figure() 
ax = plt.axes(projection='3d') 

# xdata = data[0,0]
# xdata
ax.scatter3D(data[y==0,0], data[y==0,1], data[y==0,2]);
ax.scatter3D(data[y==1,0], data[y==1,1], data[y==1,2]);
ax.scatter3D(data[y==2,0], data[y==2,1], data[y==2,2]);

plt.show()

# 马氏距离

In [10]:
def MahalanobisDistance(x,dataw):
    
    ##样本协方差矩阵
    sigma=np.cov(dataw.T)
    

    ##样本均值
    u=[]
    for i in range(sigma.shape[0]):
        u.append(np.mean(dataw[:,i]))
    u=np.array(u)

    
    ##马氏距离公式
    return (x-u).dot(np.linalg.inv(sigma)).dot((x-u).T)

    

# 问题a的求解

In [11]:
##加载测试点数据
Mx = []
Mx.append(np.array([1,2,1]))
Mx.append(np.array([5,3,2]))
Mx.append(np.array([0,0,0]))
Mx.append(np.array([1,0,0]))

##调用方法求马氏距离
for mx in Mx:
    print('测试点'+str(mx))
    for i in range(3):
        u=math.sqrt(MahalanobisDistance(mx,data[y==i]))
        print("类别"+str(i)+":  "+str(u))
    print()

测试点[1 2 1]
[[14.38051111  7.69537778  4.12232222]
 [ 7.69537778 14.62312111  3.90684   ]
 [ 4.12232222  3.90684    19.72453778]]
类别0:  1.014970621195808
[[ 36.82933444   9.98092667 -16.36675111]
 [  9.98092667  13.16855111   0.40905111]
 [-16.36675111   0.40905111  18.42121778]]
类别1:  0.8580511954300317
[[ 8.30475667  7.44494667 13.14957778]
 [ 7.44494667  8.56044889 11.60861111]
 [13.14957778 11.60861111 47.28728889]]
类别2:  2.6747570368060556

测试点[5 3 2]
[[14.38051111  7.69537778  4.12232222]
 [ 7.69537778 14.62312111  3.90684   ]
 [ 4.12232222  3.90684    19.72453778]]
类别0:  1.5571382110034355
[[ 36.82933444   9.98092667 -16.36675111]
 [  9.98092667  13.16855111   0.40905111]
 [-16.36675111   0.40905111  18.42121778]]
类别1:  1.7556806886533693
[[ 8.30475667  7.44494667 13.14957778]
 [ 7.44494667  8.56044889 11.60861111]
 [13.14957778 11.60861111 47.28728889]]
类别2:  0.6470090140927858

测试点[0 0 0]
[[14.38051111  7.69537778  4.12232222]
 [ 7.69537778 14.62312111  3.90684   ]
 [ 4.1223222

# 贝叶斯分类

In [8]:
def bayesian_classification(x_predict, Pw, dataw):
    
    ##马氏距离
    MahDistamce = MahalanobisDistance(x_predict,dataw)
    
    ##样本维数
    d = x_predict.shape[0]
    
    ##样本协方差矩阵
    sigma=np.cov(dataw.T)
    
    ##样本协方差矩阵行列式的值
    sigmaV = np.linalg.det(sigma)
    
    ##正态分布判别函数
    return (-0.5*MahDistamce) - (d/2*math.log(2*math.pi))-(0.5*math.log(sigmaV)) + (math.log(Pw))

# 问题b的求解

In [9]:
##先验概率
a =1/3
Pw = [a,a,a]

for mx in Mx:
    
    print('测试点'+str(mx))
    class_w = -1
    max_w = float('-Inf')
    for i in range(3):
        y_predict = bayesian_classification(mx, Pw[i],data[y==i])
        if max_w<y_predict:
            class_w = i
            max_w=y_predict
    
    print('分类结果： '+str(class_w))
    print(max_w)
    print()

测试点[1 2 1]
[-0.44  -1.749 -0.766]
[-0.543 -0.762 -0.542]
[3.883 1.376 1.58 ]
分类结果： 1
-8.293961583177135

测试点[5 3 2]
[-0.44  -1.749 -0.766]
[-0.543 -0.762 -0.542]
[3.883 1.376 1.58 ]
分类结果： 2
-7.078076818269081

测试点[0 0 0]
[-0.44  -1.749 -0.766]
[-0.543 -0.762 -0.542]
[3.883 1.376 1.58 ]
分类结果： 0
-7.936887968142948

测试点[1 0 0]
[-0.44  -1.749 -0.766]
[-0.543 -0.762 -0.542]
[3.883 1.376 1.58 ]
分类结果： 0
-7.935556641542461



# 问题c的求解

In [8]:
##先验概率
Pw = [0.8,0.1,0.1]
for mx in Mx:
    
    print('测试点'+str(mx))
    class_w = -1
    max_w = float('-Inf')
    for i in range(3):
        y_predict = bayesian_classification(mx, Pw[i],data[y==i])
        if max_w<y_predict:
            class_w = i
            max_w=y_predict
    
    print('分类结果： '+str(class_w))
    print(max_w)
    print()

测试点[1 2 1]
分类结果： 0
-7.456470755625868

测试点[5 3 2]
分类结果： 0
-8.153727778764054

测试点[0 0 0]
分类结果： 0
-7.061419230789047

测试点[1 0 0]
分类结果： 0
-7.060087904188561

